//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BINAES
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVITY
    {
        public int id { get; set; }
        public Nullable<System.DateTime> beginning_hour { get; set; }
        public Nullable<System.DateTime> finishing_hour { get; set; }
        public Nullable<System.DateTime> beginning_date { get; set; }
        public Nullable<System.DateTime> finishing_date { get; set; }
        public int id_area { get; set; }
        public int id_celebration { get; set; }
        public int id_attendance { get; set; }
    
        public virtual AREA AREA { get; set; }
        public virtual ATTENDANCE ATTENDANCE { get; set; }
        public virtual CELEBRATION CELEBRATION { get; set; }
    }
}
