//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BINAES
{
    using System;
    using System.Collections.Generic;
    
    public partial class GOAL
    {
        public int id { get; set; }
        public string goal_name { get; set; }
        public int id_celebration { get; set; }
    
        public virtual CELEBRATION CELEBRATION { get; set; }
    }
}
