//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BINAES
{
    using System;
    using System.Collections.Generic;
    
    public partial class LABEL_
    {
        public int id { get; set; }
        public string label_name { get; set; }
        public int id_copy { get; set; }
    
        public virtual COPY_ COPY_ { get; set; }
    }
}
