//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BINAES.SQL_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTENDANCE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ATTENDANCE()
        {
            this.ACTIVITY = new HashSet<ACTIVITY>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> entrance_date { get; set; }
        public Nullable<System.DateTime> exit_date { get; set; }
        public Nullable<System.DateTime> entarance_hour { get; set; }
        public Nullable<System.DateTime> exit_hour { get; set; }
        public int id_user { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVITY> ACTIVITY { get; set; }
        public virtual USER_ USER_ { get; set; }
    }
}
