//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BINAES.SQL_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class CELEBRATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CELEBRATION()
        {
            this.ACTIVITY = new HashSet<ACTIVITY>();
            this.GOAL = new HashSet<GOAL>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string picture { get; set; }
        public Nullable<int> attendance { get; set; }
        public Nullable<System.DateTime> beginning_hour { get; set; }
        public Nullable<System.DateTime> finishing_hour { get; set; }
        public Nullable<System.DateTime> beginning_date { get; set; }
        public Nullable<System.DateTime> finishing_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVITY> ACTIVITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GOAL> GOAL { get; set; }
    }
}
