//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BINAES.SQL_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class COLLECTION_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COLLECTION_()
        {
            this.COPY_ = new HashSet<COPY_>();
        }
    
        public int id { get; set; }
        public string collection_name { get; set; }
        public Nullable<int> id_type { get; set; }
        public Nullable<int> id_genre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COPY_> COPY_ { get; set; }
        public virtual GENRE GENRE { get; set; }
        public virtual TYPE_ TYPE_ { get; set; }
    }
}
