//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BINAES.SQL_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAN_BOOKING
    {
        public int id { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public Nullable<System.DateTime> expected_loan_timestamp { get; set; }
        public Nullable<System.DateTime> expected_return_timestamp { get; set; }
        public Nullable<System.DateTime> loan_timestamp { get; set; }
        public Nullable<System.DateTime> return_timestamp { get; set; }
        public int id_user { get; set; }
        public int id_copy { get; set; }
    
        public virtual COPY_ COPY_ { get; set; }
        public virtual USER_ USER_ { get; set; }
    }
}
