//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BINAES.SQL_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER_()
        {
            this.ATTENDANCE = new HashSet<ATTENDANCE>();
            this.LOAN_BOOKING = new HashSet<LOAN_BOOKING>();
        }
    
        public int id { get; set; }
        public string user_full_name { get; set; }
        public string username { get; set; }
        public string user_address { get; set; }
        public string phone { get; set; }
        public byte[] picture { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public int id_occupancy { get; set; }
        public int id_institution { get; set; }
        public int id_role { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTENDANCE> ATTENDANCE { get; set; }
        public virtual INSTITUTION INSTITUTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOAN_BOOKING> LOAN_BOOKING { get; set; }
        public virtual OCCUPANCY OCCUPANCY { get; set; }
        public virtual ROLE_ ROLE_ { get; set; }
    }
}
